import { Urls } from "@/shared/constants/urls";
export const matchedUrls = [
  Urls.OUR_PARTNERS,
  Urls.HIGHLIGHTS,
  Urls.EVENT_MEMORIES,
  Urls.HIGHLIGHTS_INNER,
  Urls.EVENT_MEMORIES_CATEGORY,
  Urls.EVENT_MEMORIES_CATEGORY_INNER,
  Urls.OUR_HISTORY,
  Urls.TICKET_INFO,
  Urls.HALLS,
  Urls.RULES,
  Urls.RULES_INNER,
  Urls.CATERING_INFORMATION,
  Urls.FAQ,
  Urls.CONTACT,
  Urls.YOUR_VISIT,
  Urls.YOUR_VISIT_EXPERIENCE,
  Urls.YOUR_VISIT_GETTING,
  Urls.YOUR_VISIT_HOTELS,
  Urls.YOUR_VISIT_RESTAURANTS,
  Urls.TOUR
];
