export const enum Urls {
  HOME = "/",
  OUR_PARTNERS = "/our-partners",
  HIGHLIGHTS = "/events/highlights",
  HIGHLIGHTS_INNER = "/events/highlights/:slug",
  EVENT_MEMORIES = "/events/memories",
  EVENT_MEMORIES_CATEGORY = "/events/memories/:category",
  EVENT_MEMORIES_CATEGORY_INNER = "/events/memories/:category/:slug",
  OUR_HISTORY = "/about/our-history",
  TICKET_INFO = "/about/ticket-information",
  HALLS = "/halls",
  HALLS_INNER = "/halls/:slug",
  RULES = "/about/rules",
  RULES_INNER = "/about/rules/:inner",
  CATERING_INFORMATION = "/about/catering-info",
  FAQ = "/faq",
  CONTACT = "/contact",
  YOUR_VISIT = "/your-visit",
  YOUR_VISIT_HOTELS = "/your-visit/hotels",
  YOUR_VISIT_HOTELS_INNER = "/your-visit/hotels/:inner",
  YOUR_VISIT_RESTAURANTS = "/your-visit/restaurants",
  YOUR_VISIT_RESTAURANTS_INNER = "/your-visit/restaurants/:inner",
  YOUR_VISIT_EXPERIENCE= "/your-visit/experience-in-baku",
  YOUR_VISIT_EXPERIENCE_INNER= "/your-visit/experience-in-baku/:inner",
  YOUR_VISIT_GETTING = "/your-visit/getting-here",
  TOUR = "/tour",
}
